#!/usr/bin/env bash

set -e

source /etc/os-release

CFG_FILE="install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_PLUGINS="${BASEDIR}/dotbot-plugins"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_CFG_DIR="${BASEDIR}/dotbot-config"
FINAL_CFG_DIR="${DEFAULT_CFG_DIR}/final_common"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

if [[ $ID == "debian" ]] || [[ $ID_LIKE == "debian" ]]; then
	PLATFORM_CFG_DIR="${DEFAULT_CFG_DIR}/debian"
elif [[ $ID == "arch" ]] || [[ $ID_LIKE == "arch" ]]; then
	PLATFORM_CFG_DIR="${DEFAULT_CFG_DIR}/arch"
fi

paths = ( ${DEFAULT_CFG_DIR} ${PLATFORM_CFG_DIR} ${FINAL_CFG_DIR} )

for dir in paths
do
    echo $dir
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${dir}" -c "${dir}/${CFG_FILE}" --plugin-dir "${BASEDIR}/.plugins"
done


